# -*- coding: utf-8 -*-
"""multi_agent_tool-calling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eoO0w2D4UeS9ksQ4tVyt3jrYNr91Zche
"""

!pip install -q groq

import os
import json
from groq import Groq
from getpass import getpass
os.environ["GROQ_API_KEY"] = getpass("Enter your GROQ_API_KEY:")
client = Groq(api_key=os.environ["GROQ_API_KEY"])
MODEL = "openai/gpt-oss-120b"

def get_customer(customer_id):
    customers = {
        "C101": {
            "name": "Rahul",
            "plan": "Premium"
        },
        "C102": {
            "name": "Priya",
            "plan": "Basic"
        }
    }
    return customers.get(customer_id, "Customer not found")

def get_order(order_id):
    orders = {
        "ORD1001": {
            "customer_id": "C101",
            "status": "Shipped",
            "amount": 2500
        },
        "ORD1002": {
            "customer_id": "C102",
            "status": "Delivered",
            "amount": 1800
        }
    }

    return orders.get(order_id, "Order not found")

def calculate_refund(amount, percentage):
    return amount * percentage / 100

available_tools = {
    "get_customer": get_customer,
    "get_order": get_order,
    "calculate_refund": calculate_refund
}

tools = [
    {
        "type": "function",
        "function": {
            "name": "get_customer",
            "description": "Get customer information using a customer ID.",
            "parameters": {
                "type": "object",
                "properties": {
                    "customer_id": {
                        "type": "string",
                        "description": "The customer ID, for example C101 or C102."
                    }
                },
                "required": ["customer_id"]
            }
        }
    },

    {
        "type": "function",
        "function": {
            "name": "get_order",
            "description": "Get order information using an order ID.",
            "parameters": {
                "type": "object",
                "properties": {
                    "order_id": {
                        "type": "string",
                        "description": "The order ID, for example ORD1001 or ORD1002."
                    }
                },
                "required": ["order_id"]
            }
        }
    },

    {
        "type": "function",
        "function": {
            "name": "calculate_refund",
            "description": "Calculate a refund amount from an original amount and refund percentage.",
            "parameters": {
                "type": "object",
                "properties": {
                    "amount": {
                        "type": "number",
                        "description": "Original transaction amount."
                    },
                    "percentage": {
                        "type": "number",
                        "description": "Refund percentage."
                    }
                },
                "required": ["amount", "percentage"]
            }
        }
    }
]

def run_agent(user_request, max_iterations=5):

    messages = [
        {
            "role": "system",
            "content": """
            You are an operations assistant. You have access to tools.
            Use the tools whenever the user asks for customer, order, or refund information.

            Never invent information.

            Continue using tools until the user's question has been completely answered."""
        },
        {
            "role": "user",
            "content": user_request
        }
    ]

    for iteration in range(max_iterations):

        print(f"\n========== ITERATION {iteration + 1} ==========")

        response = client.chat.completions.create(
            model=MODEL,
            messages=messages,
            tools=tools,
            tool_choice="auto"
        )

        assistant_message = response.choices[0].message

        messages.append(assistant_message)

        # --------------------------------
        # Agent has finished
        # --------------------------------

        if not assistant_message.tool_calls:

            print("Agent decided it is finished.")

            return assistant_message.content

        # --------------------------------
        # Execute requested tools
        # --------------------------------

        for tool_call in assistant_message.tool_calls:

            name = tool_call.function.name

            arguments = json.loads(tool_call.function.arguments)

            print(f"Tool requested: {name}")
            print(f"Arguments: {arguments}")

            if name not in available_tools:
                result = {
                    "error": f"Unknown tool: {name}"
                }

            else:
                function = available_tools[name]

                result = function(**arguments)

            print(f"Tool result: {result}")

            messages.append({
                "role": "tool",
                "tool_call_id": tool_call.id,
                "name": name,
                "content": json.dumps(result)
            })

    return "Agent stopped because maximum iterations were reached."

answer = run_agent(
    """
    Find customer C102,
    check their order ORD1002,
    and tell me the order status.
    """
)

print("\nFINAL ANSWER:")
print(answer)

answer = run_agent(
    """
    Please investigate customer C102.
    I want to know who the customer is, what plan they have,
    whether their order ORD1002 has been delivered,
    and if it has been delivered, calculate a 20% refund
    on the order amount.
    """
)

print(answer)