# -*- coding: utf-8 -*-
"""single_agent_tool-calling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fIaEakEKMby33BNa9JVHFlQgwwlwSxaI
"""

!pip install -q groq

import os
import json
from groq import Groq
from getpass import getpass
os.environ["GROQ_API_KEY"] = getpass("Enter your GROQ_API_KEY:")
client = Groq(api_key=os.environ["GROQ_API_KEY"])
MODEL = "openai/gpt-oss-120b"

def calculate(a, b, operation):
    if operation == "add":
        return a + b
    elif operation == "subtract":
        return a - b
    elif operation == "multiply":
        return a * b
    elif operation == "divide":
        return a / b
    else:
        return "Unknown operation"

tools = [
    {
        "type": "function",
        "function": {
            "name": "calculate",
            "description": "Perform mathematical calculations and operations",
            "parameters": {
                "type": "object",
                "properties": {
                    "a": {
                        "type": "number",
                        "description": "First number"
                    },
                    "b": {
                        "type": "number",
                        "description": "Second number"
                    },
                    "operation": {
                        "type": "string",
                        "enum": [
                            "add",
                            "subtract",
                            "multiply",
                            "divide"
                        ],
                        "description": "Mathematical operations"
                    }
                },
                "required": ["a", "b", "operation"]
            }
        }
    }
]

messages = [
    {
        "role": "system",
        "content": "You are a helpful mathematical assistant."
    },
    {
        "role": "user",
        "content": "What is 25 multiplied by 16?"
    }
]

response = client.chat.completions.create(
    model= MODEL,
    messages= messages,
    tools= tools,
    tool_choice= "auto"
)

message = response.choices[0].message
print(message)

print(message.tool_calls)

import json

def calculate(a, b, operation):
    if operation == "add":
        return a + b
    elif operation == "subtract":
        return a - b
    elif operation == "multiply":
        return a * b
    elif operation == "divide":
        return a / b
    return None

available_functions = {"calculate": calculate}

import json

messages = [
    {
        "role": "system",
        "content": (
            "You are a helpful mathematical assistant. "
            "Use the calculator tool whenever calculations are required."
        ),
    },
    {
        "role": "user",
        "content": "Calculate 25 * 16 and then add 100.",
    },
]

while True:
    response = client.chat.completions.create(
        model=MODEL,
        messages=messages,
        tools=tools,
        tool_choice="auto",
    )

    assistant_message = response.choices[0].message
    messages.append(assistant_message)

    if not assistant_message.tool_calls:
        print(assistant_message.content)
        break

    # Execute every tool call
    for tool_call in assistant_message.tool_calls:
        function_name = tool_call.function.name
        arguments = json.loads(tool_call.function.arguments)

        function = available_functions[function_name]
        result = function(**arguments)

        messages.append(
            {
                "role": "tool",
                "tool_call_id": tool_call.id,
                "name": function_name,
                "content": str(result),
            }
        )